
spring:
    
   profiles:
       
   active:
         
   - dev


---

spring:
    
   profiles: dev
    
   application:
         
       name: microservicecloud-config-hiway-dev


---

spring:
    
   profiles: test
    
   application:
        
       name: microservicecloud-config-hiway-test